version: "3"
services:
  next:
    image: node:16.18.0-alpine
    tty: true
    working_dir: /next-app
    command: "npm run dev"
    env_file:
      - ./docker/.env.local
    volumes:
      - ./next-app:/next-app/
    ports:
      - 3000:3000

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    tty: true
    restart: always
    env_file:
      - ./docker/db.env
    volumes:
      - ./api:/go/src/app
    ports:
      - 8080:8080
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    tty: true
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - next

  mysql:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    env_file:
      - ./docker/db.env
    tty: true
    volumes:
      - ./db/initdb.d:/initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
