version: "3"
services:
  next:
    container_name: Next-app
    build:
      context: .
      dockerfile: ./next-app/Dockerfile
    tty: true
    volumes:
      - ./next-app:/next-app/
    ports:
      - 3000:3000

  go:
    container_name: Go-app
    build:
      context: .
      dockerfile: ./go-app/Dockerfile
    tty: true
    volumes:
      - ./go-app:/go-app/
    ports:
      - 8000:8000

  nginx:
    image: nginx
    container_name: nginx_container
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  mysql:
    container_name: mysql_contianer
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql/initdb.d:/initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    links:
      - go

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    links:
      - mysql
    ports:
      - 1234:80
    volumes:
      - /sessions
