USE portfolio_hub;

DROP TABLE IF EXISTS users
CREATE TABLE users (
  id VARCHAR(128) PRIMARY KEY NOT NULL,
  name VARCHAR(64) NOT NULL,
  photo_url VARCHAR(256) NOT NULL
);

DROP TABLE IF EXISTS portfolios
CREATE TABLE portfolios (
  id SERIAL PRIMARY KEY,
  CONSTRAINT uid
    FOREIGN KEY (id)
    REFERENCES users (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  title VARCHAR(64) NOT NULL,
  portfolio_url VARCHAR(256) NOT NULL
);